### ISSUE TITLE
Delete datasets from the worker and validator nodes; once they're finished training and testing models

### ISSUE THREAD

**Issue by Trabing** [morphware/daemon#124]
We need to add a small script that deletes the datasets from the worker and validator nodes; once they're finished training and testing models

Perhaps something like `rm` or `rmdir`, depending on the operating system

**Comment by darshanraju** [comment]
A worker should remove the files once it knows the validator has downloaded them. The only way this happens at the moment is if the worker listens for the approveJob action initiated by the validator. And even then, thats only called if the model error is acceptable.

Proposals
- Have a method to 'rejectJob' in the contract to call when the model accuracy is insufficient.

thoughts @Trabing

**Comment by darshanraju** [comment]
closes https://github.com/morphware/daemon/pull/140
